defaults:
  - _self_
  - override hydra/launcher:  local
  - override hydra/output:  local


# snapshot
save_snapshot: false
save_freq: 10000
load_snap: ""
linear_probe: false
finetune_lang_reward: false
finetune_bn_layers: false
freeze_convnet: false
freeze_lang_reward: false
# replay buffer
num_workers: 10
batch_size: 16 
train_steps: 1000000
eval_freq: 20000
# misc
seed: 1
device: cuda
# experiment
experiment: train_r3m
# agent
lr: 1e-4
# data
alpha: 0.2
dataset: "rlbench"
wandbproject: 
wandbuser: 
wandb: false
doaug: "rctraj"
manifest_path: 

agent:
  _target_: r3m.R3M
  device: ${device}
  lr: ${lr}
  hidden_dim: 1024
  size: 50
  l2weight: 0.00001
  l1weight: 0.00001
  tcnweight: 1.0
  langweight: 1.0
  l2dist: true
  bs: ${batch_size}
  linear_probe: ${linear_probe}
  finetune_lang_reward: ${finetune_lang_reward}
  finetune_bn_layers: ${finetune_bn_layers}
  freeze_convnet: ${freeze_convnet}
